codecov:
  require_ci_to_pass: yes

coverage:
<<<<<<< HEAD
  range: 60..90
  status:
    project:
      default:
=======
  status:
    project:
      default: false
      server:
>>>>>>> c3bd8892e6 (fix: in case of owner, always include owner in count data)
        target: auto
        threshold: 0.5%
        flags:
          - server
    patch:
<<<<<<< HEAD
      default:
=======
      default: false
      server:
>>>>>>> c3bd8892e6 (fix: in case of owner, always include owner in count data)
        target: 85%
        threshold: 0%
        only_pulls: true
        if_ci_failed: ignore
        flags:
          - server

comment:
  layout: "diff, flags"
  require_changes: true
<<<<<<< HEAD
  show_critical_paths: true
=======
>>>>>>> c3bd8892e6 (fix: in case of owner, always include owner in count data)

flags:
  server:
    paths:
<<<<<<< HEAD
      - "**/*.py"
    carryforward: true
  ui-tests:
    paths:
      - "**/*.js"
    carryforward: true
  server-ui:
    paths:
      - "**/*.py"
    carryforward: true

profiling:
   critical_files_paths:
      - /frappe/api.py
      - /frappe/app.py
      - /frappe/auth.py
      - /frappe/boot.py
      - /frappe/client.py
      - /frappe/handler.py
      - /frappe/migrate.py
      - /frappe/sessions.py
      - /frappe/utils/*
      - /frappe/desk/reportview.py
      - /frappe/desk/form/*
      - /frappe/model/*
      - /frappe/core/doctype/doctype/*
      - /frappe/core/doctype/data_import/*
      - /frappe/core/doctype/user/*
      - /frappe/core/doctype/user/*
      - /frappe/query_builder/*
      - /frappe/database/*
=======
      - ".*\\.py"
    carryforward: true
  ui-tests:
    paths:
      - ".*\\.js"
    carryforward: true
>>>>>>> c3bd8892e6 (fix: in case of owner, always include owner in count data)
