blank_issues_enabled: false
contact_links:
  - name: Community Forum
<<<<<<< HEAD
    url: https://discuss.frappe.io/c/framework/5
=======
    url: https://discuss.erpnext.com/
>>>>>>> c3bd8892e6 (fix: in case of owner, always include owner in count data)
    about: For general QnA, discussions and community help.
