name: Generate Semantic Release
on:
  push:
    branches:
<<<<<<< HEAD
      - version-15
=======
      - version-14-beta
>>>>>>> 4509e75179 (fix: convert frappe.boot to JSON properly)
permissions:
  contents: read

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Entire Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: false
      - name: Setup Node.js
<<<<<<< HEAD
        uses: actions/setup-node@v3
=======
        uses: actions/setup-node@v4
>>>>>>> 4509e75179 (fix: convert frappe.boot to JSON properly)
        with:
          node-version: 20
      - name: Setup dependencies
        run: |
          npm install @semantic-release/git @semantic-release/exec --no-save
      - name: Create Release
        env:
          GH_TOKEN: ${{ secrets.RELEASE_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}
          GIT_AUTHOR_NAME: "Frappe PR Bot"
          GIT_AUTHOR_EMAIL: "developers@frappe.io"
          GIT_COMMITTER_NAME: "Frappe PR Bot"
          GIT_COMMITTER_EMAIL: "developers@frappe.io"
        run: npx semantic-release
